- hosts: all
  become: yes

  vars:
    #Add your details below in quotes.
    git_author_user_name:
    git_author_email:
  
  tasks:
    - name: Copy a .ssh config file to disable ssh known host checking
      ansible.builtin.copy:
        src: config
        dest: /root/.ssh/config

    - name: Making a data directory... How could that be bad?
      ansible.builtin.file:
        path: /root/code_data
        state: directory
        mode: '0755'

    - name: Making another directory in a suspect location.
      ansible.builtin.file:
        path: /root/bin
        state: directory
        mode: '0755'

    - name: Copy a simple bash script
      ansible.builtin.copy:
        src: run_code
        dest: /root/bin
        mode: a+x
        
    - name: What would my security friends say about this playbook!?
      ansible.builtin.debug:
        msg:
        - "Are you really going to make it easy to run VSCode as SUPER USER!!?"
        - "This is just irresponsible.  Don't share this code."
        - "You created a dir that was already in path vs adding a new dir to path?  Working hard to be lazy."

    - name: Might as well install VIM.
      ansible.builtin.yum:
        name: vim
        state: present

    - name: Set git author name using command while we're at it.
      ansible.builtin.command:
        command: git config --global user.name "{{ git_author_username }}"
      when: git_author_username is defined

    - name: Set git author email using command module too.
      ansible.builtin.command:
        command: git config --global user.email "{{ git_author_email }}"
      when: git_author_email is defined

